spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/yupi?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://mikufans.mysql.polardb.rds.aliyuncs.com/gumi?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123123
  redis:
    host: r-bp1geol1jckr3gycxq.redis.rds.aliyuncs.com
    port: 6379
    password: Zlzzdpsczn9430 # 如果有密码需要填写
    database: 0

#session失效时间
  session:
    timeout: 86400
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体变量名
      logic-delete-value: 1 #逻辑已删除值 设置为1
      logic-not-delete-value: 0 #逻辑未删除的值 设置为0
logging:
  level:
    your.package.mapper: DEBUG

